FROM debian:buster-slim

LABEL maintainer=cfb@liquidreality.org
LABEL description="Example base image"

ENV DEBIAN_FRONTEND noninteractive

# Make sure we have the freshest
RUN apt-get -q update               \
&&  apt-get -y autoremove           \
&&  apt-get -y clean                \
&&  rm -rf /var/lib/apt/lists/*

LABEL \
  org.label-schema.schema-version="1.0"                                     \
  org.label-schema.vendor="Chet Burgess"                                    \
  org.label-schema.name="Docker Examples Base"                              \
  org.label-schema.version="latest"                                         \
  org.label-schema.url="https://github.com/cburgess/docker-examples"        \
  org.label-schema.vcs-url="https://github.com/cburgess/docker-examples"    \
  license="Apache-2.0"
